// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IWebHtml interface {
		ReturnIndexHtml(r *ghttp.Request, username string)
	}
)

var (
	localWebHtml IWebHtml
)

func WebHtml() IWebHtml {
	if localWebHtml == nil {
		panic("implement not found for interface IWebHtml, forgot register?")
	}
	return localWebHtml
}

func RegisterWebHtml(i IWebHtml) {
	localWebHtml = i
}
